server:
  host: ""
  port: 9990
  certPath: certs
  cacheFile: cache/cache.json
  userCacheFile: cache/user.json

proxies:
  # - url: http://127.0.0.1:8880
  # - url: http://127.0.0.1:8888
  # - url: http://127.0.0.1:9994
  #   blacklist:
  #     - \.*vpn\.*
  #   whitelist:
  #     - \\.com$

timeouts:
  checkProxy:
    TLSHandshakeTimeout: 1800
    responseHeaderTimeout: 2500
    expectContinueTimeout: 500
    dialContext: 1000
    timeout: 3000
  clientConnection:
    timeout: 30000
    keepAlive: 30000


dpi:
  uploadProbe:
    totalSizeKB: 3840
    chunkSizeKB: 160
    delayMS: 30
  retryAttempts: 1
  usePUTinRechecks: false

cache:
  ttl: 2h
  maxAge: 240h
  saveTime: 5m
  cleanupInterval: 12h

userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36"
